"""Configuration constants for Archive Search V11."""

from __future__ import annotations

from pathlib import Path

APP_TITLE = "Archive Search V11"

ARCHIVE_SEARCH_PRIMARY_FOLDER = Path(r"C:\\Primary Folder")
ARCHIVE_SEARCH_SECONDARY_FOLDER = Path(r"C:\\Secondary Folder")

OPENPYXL_EXTENSIONS = {".xlsx", ".xlsm", ".xltx", ".xltm"}
XLRD_EXTENSIONS = {".xls"}
XLSB_EXTENSIONS = {".xlsb"}
WORKBOOK_EXTENSIONS = OPENPYXL_EXTENSIONS | XLRD_EXTENSIONS | XLSB_EXTENSIONS

WORD_XML_EXTENSIONS = {".docx", ".docm", ".dotx", ".dotm"}
WORD_LEGACY_EXTENSIONS = {".doc"}
WORD_EXTENSIONS = WORD_XML_EXTENSIONS | WORD_LEGACY_EXTENSIONS

PDF_EXTENSIONS = {".pdf"}
PLAIN_TEXT_EXTENSIONS = {".txt"}
TEXT_DOCUMENT_EXTENSIONS = WORD_EXTENSIONS | PDF_EXTENSIONS | PLAIN_TEXT_EXTENSIONS
ALL_INDEXED_EXTENSIONS = WORKBOOK_EXTENSIONS | TEXT_DOCUMENT_EXTENSIONS

INDEX_DB_PREFIX = ".archive_search_"
INDEX_SCHEMA_VERSION = 5
INDEX_BATCH_SIZE = 25

INDEX_RETRY_ATTEMPTS = 4
INDEX_RETRY_DELAY_SECONDS = 0.75
INDEX_STABLE_PROBE_DELAY_SECONDS = 0.25
STATUS_UPDATE_INTERVAL_SECONDS = 0.35
RESULT_BATCH_SIZE = 20
RESULT_LIMIT = 250
DETAIL_SNIPPETS_PER_FILE = None  # Show every matching snippet in the details pane.
DETAIL_PREVIEW_LENGTH = 700

HIGHLIGHT_TAG_NAME = "match_highlight"
HIGHLIGHT_BACKGROUND = "#fff59d"
HIGHLIGHT_FOREGROUND = "#000000"
